### PR TITLE
Flake: add support for aarch64-darwin

### PR DESCRIPTION
**Pull request by vtuan10**
This adds support for Apple Silicon (aarch64-darwin).
As [naersk](https://github.com/nmattia/naersk) does not support aarch64-darwin yet, we use our own fork for now.

### CODE REVIEW

**Comment by veehaitch** [comment]
Great 🙏🏻 

1. I think you should go ahead and open a PR with [nmattia/naersk](https://github.com/nmattia/naersk). Having this change upstream makes sense for us and anybody else.
2. We should add an additional GitHub Actions job which builds `ragenix` for `aarch64-darwin`. The current macOS job only builds it for `x86_64-darwin`.

**Comment by vtuan10** [comment]
Thanks for your review
1. I created a PR at naersk: https://github.com/nmattia/naersk/pull/182
2. Added a workflow file which builds on aarch64-darwin

**Comment by vtuan10** [comment]
Currently, I implemented the github action workflow for aarch64-darwin without nix. There seems to be some problems in getting a functional crosscompilation from an x86_64-darwin machine to an aarch64-darwin.

By applying the `--target` flag, rust successfully attempts to build for aarch64-darwin. Unfortunately, using `nix build` fails as it tries to link x86_64-darwin libraries to an arm64 executeable. Cross compilation in nix is, therefore, needed. 

Using `crossSystem = { config = "aarch64-apple-darwin"; };` does not work, it seems there is no `llvmPackages_11` for aarch64-darwin.

**Review by veehaitch — APPROVED** [review]
Let's merge this to have native ragenix support for `aarch64-darwin` after all.

**Pull request merged**
